apiVersion: apps/v1
kind: Deployment
metadata:
  name: wisecom-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wisecow
  template:
    metadata:
      labels:
        app: wisecow
    spec:
      containers:
      - name: wisecom
        image: akshathapg/wisecow
        ports:
        - containerPort: 4499
